// nextJS
import type { Metadata } from "next";
import { Barlow, Inter } from "next/font/google";
import "./globals.css";
// Theme
import { ThemeProvider } from "next-themes";
// Clerk
import {
  ClerkProvider,
} from '@clerk/nextjs';

const inter = Inter({ subsets: ["latin"] });
const barlowFont = Barlow({ subsets: ["latin"], weight: ['500', '700'], variable: '--font-barlow' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${barlowFont.variable} ${inter.className}`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
          >
            {children}
          </ThemeProvider>

        </body>

      </html>
    </ClerkProvider>
  );
}
